// popover funtionality
$(document).ready(function(){
    $('[data-toggle="popover"]').popover(); 
});

// adj1 array
var adjOne = [{wrd: "apish", def: "foolish; resembling an ape"}, {wrd: "artless", def: "crude, unskillful"}, {wrd: "beslubbering", def: "smear, smeared; slobbering"}, {wrd: "calumniating", def: "uttering maliciously false statements"}, {wrd: "cautelous", def: "crafty, deceitful"}, {wrd: "churlish", def: "rude, vulgar"}, {wrd: "coldblooded", def: "emotionless"}, {wrd: "concupiscible", def: "desirous, lustful"}, {wrd: "covetous", def: "greedy; envious of the posessions of others"}, {wrd: "crudy", def: "thick, as in 'curdy'"}, {wrd: "cuckoldly", def: "haplessly victimized"}, {wrd: "deceptious", def: "deceiving, delusive"}, {wrd: "degenerate", def: "lacking morals"}, {wrd: "facinerious", def: "extremely wicked and vile"}, {wrd: "fawning", def: "giving exaggerated praise to gain favor"}, {wrd: "finical", def: "foppish in matters of dress; fussily fastidious"}, {wrd: "fusty", def: "moldy, stale"}, {wrd: "goatish", def: "lustful"}, {wrd: "gorbellied", def: "big bellied, fat paunched"}, {wrd: "greasy", def: "oily; insincerely polite"}, {wrd: "heinous", def: "outrageously wicked, odious, atrocious"}, {wrd: "incontinent", def: "indulging lust without restraint"}, {wrd: "inexecrable", def: "unable to be overly execrated or detested"}, {wrd: "insolent", def: "rude, disrespectful"}, {wrd: "lecherous", def: "excessively sex-driven"}, {wrd: "lisping", def: "speaking childishly, or affectedly"}, {wrd: "loathly", def: "disgusting, repuslive"}, {wrd: "lubberly", def: "awkward, clumsy, loutish"}, {wrd: "lumpish", def: "poorly formed; stupid"}, {wrd: "mammering", def: "hesitating, stammering"}, {wrd: "musty", def: "moldy, stale; to emit a bad smell"}, {wrd: "naughty", def: "wicked, worthless; had a stronger meaning in Shakespeare's time"}, {wrd: "obscene", def: "repugnant, morally offensive"}, {wrd: "overgorged", def: "gluttonously stuffed"}, {wrd: "panderly", def: "small; insignificant"}, {wrd: "pestiferous", def: "annoying, troublesome; dangerous to society; associated with the 'pest' or 'plague'"}, {wrd: "plumpy", def: "fat"}, {wrd: "puking", def: "vomiting"}, {wrd: "rascally", def: "untrustworthy"}, {wrd: "reeky", def: "reeking, bad-smelling"}, {wrd: "sanctimonious", def: "hypocritically self-righteous"}, {wrd: "sickly", def: "ill, feeble"}, {wrd: "slobbery", def: "wet, slovenly, muddy"}, {wrd: "sneaping", def: "biting, nipping"}, {wrd: "spongy", def: "soft"}, {wrd: "stinking", def: "foul-smelling"}, {wrd: "superserviceable", def: "overeager to be of service, officious"}, {wrd: "thrasonical", def: "boastful, bragging; named after 'Thraso,' a braggart soldier in an ancient Roman comedy"}, {wrd: "unhandsome", def: "ugly"}, {wrd: "unwiped", def: "unwashed, unclean"}, {wrd: "viperous", def: "venomous, malignant"}, {wrd: "wanton", def: "promiscuous, immodest"}, {wrd: "warped", def: "twisted, deformed"}, {wrd: "witless", def: "without intelligence, stupid"},]

// adj2 array
var adjTwo = []

// noun array
var noun = []

